// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0--rc2
// source: thumbnail.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Thumbnail_GetThumbnail_FullMethodName = "/api.Thumbnail/GetThumbnail"
)

// ThumbnailClient is the client API for Thumbnail service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThumbnailClient interface {
	GetThumbnail(ctx context.Context, in *GetThumbnailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetThumbnailResponse], error)
}

type thumbnailClient struct {
	cc grpc.ClientConnInterface
}

func NewThumbnailClient(cc grpc.ClientConnInterface) ThumbnailClient {
	return &thumbnailClient{cc}
}

func (c *thumbnailClient) GetThumbnail(ctx context.Context, in *GetThumbnailRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetThumbnailResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Thumbnail_ServiceDesc.Streams[0], Thumbnail_GetThumbnail_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetThumbnailRequest, GetThumbnailResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Thumbnail_GetThumbnailClient = grpc.ServerStreamingClient[GetThumbnailResponse]

// ThumbnailServer is the server API for Thumbnail service.
// All implementations must embed UnimplementedThumbnailServer
// for forward compatibility.
type ThumbnailServer interface {
	GetThumbnail(*GetThumbnailRequest, grpc.ServerStreamingServer[GetThumbnailResponse]) error
	mustEmbedUnimplementedThumbnailServer()
}

// UnimplementedThumbnailServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThumbnailServer struct{}

func (UnimplementedThumbnailServer) GetThumbnail(*GetThumbnailRequest, grpc.ServerStreamingServer[GetThumbnailResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetThumbnail not implemented")
}
func (UnimplementedThumbnailServer) mustEmbedUnimplementedThumbnailServer() {}
func (UnimplementedThumbnailServer) testEmbeddedByValue()                   {}

// UnsafeThumbnailServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThumbnailServer will
// result in compilation errors.
type UnsafeThumbnailServer interface {
	mustEmbedUnimplementedThumbnailServer()
}

func RegisterThumbnailServer(s grpc.ServiceRegistrar, srv ThumbnailServer) {
	// If the following call pancis, it indicates UnimplementedThumbnailServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Thumbnail_ServiceDesc, srv)
}

func _Thumbnail_GetThumbnail_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetThumbnailRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ThumbnailServer).GetThumbnail(m, &grpc.GenericServerStream[GetThumbnailRequest, GetThumbnailResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Thumbnail_GetThumbnailServer = grpc.ServerStreamingServer[GetThumbnailResponse]

// Thumbnail_ServiceDesc is the grpc.ServiceDesc for Thumbnail service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Thumbnail_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Thumbnail",
	HandlerType: (*ThumbnailServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetThumbnail",
			Handler:       _Thumbnail_GetThumbnail_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "thumbnail.proto",
}
