// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/User/GolandProjects/github.com/Ktuty/gRPC_thumbnails/pkg/api/thumbnail.pb.go

// Package mocks is a generated GoMock package.
package mocks
