// Code generated by MockGen. DO NOT EDIT.
// Source: C:/Users/User/GolandProjects/github.com/Ktuty/gRPC_thumbnails/internal/services/thumbnail.go

// Package mocks is a generated GoMock package.
package mocks
